### ISSUE TITLE
how to develop new stages on spinnaker?

### ISSUE THREAD

**Issue by lettrung99** [spinnaker/spinnaker.github.io#314] opened 2017-08-14 23:58 UTC
Page: /setup/install/

Feedback:  Hello, do we have more guides on how to develop new stages on spinnaker?

**Comment by skim1420** [comment] 2017-08-18 18:25
Duplicate of https://github.com/spinnaker/spinnaker.github.io/issues/313

**Closed as completed by skim1420** 2017-08-18 18:25 UTC
