### ISSUE TITLE
supplying "--region" is not allowed

### ISSUE THREAD

**Issue by avineshwar** [spinnaker/spinnaker.github.io#271] opened 2017-07-16 00:33 UTC
Page: /setup/storage/s3/

Feedback:

Remove the "--region" parameter/flag/argument for a successful bucket creation.

**Comment by ttomsu** [comment] 2017-07-19 14:15
@jervi

**Comment by lwander** [comment] 2017-08-01 14:51
Can you elaborate?

**Comment by ttomsu** [comment] 2017-09-18 15:24
Closing - please reopen if the issue is not resolved.

**Closed as completed by ttomsu** 2017-09-18 15:24 UTC
